// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package storm

type NewChannel struct {
	Node1    string `json:"node1"`
	Node2    string `json:"node2"`
	Capacity int    `json:"capacity"`
}

type NewNode struct {
	PubKey string `json:"pubKey"`
	Name   string `json:"name"`
}
