// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package storm

type NewChannel struct {
	Node     []*NewChannelNode `json:"node"`
	Capacity int               `json:"capacity"`
}

type NewChannelNode struct {
	UID string `json:"uid"`
}

type NewNode struct {
	PubKey string `json:"pubKey"`
	Name   string `json:"name"`
}
